[[cases]]
text = "Who's on first?"
tokens = ["Who's", "on", "first"]

[[cases]]
text = "What's on second?"
tokens = ["What's", "on", "second"]

[[cases]]
text = ""

[[cases]]
text = "2<=5"
tokens = ["2<=5"]